spring:
  application:
    name: stoicron-back
  mongodb:
    uri: ${STOICRONBACK_DB_URI:mongodb://root:root@localhost:28000/stoicron_db?authSource=admin}
    database: ${STOICRONBACK_DB_NAME:stoicron_db}
    username: ${STOICRONBACK_DB_USER:root}
    password: ${STOICRONBACK_DB_PASS:root}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.authentication: TRACE



server:
  port: ${STOICRONBACK_PORT:5000}

application:
  security:
    jwt:
      secret: ${STOICRONBACK_JWT_SECRET:your_jwt_secret_key}
      expiration-ms: ${STOICRONBACK_JWT_EXPIRATION_MS:3600000} # 1 hour in milliseconds
      refresh-expiration-ms: ${STOICRONBACK_JWT_REFRESH_EXPIRATION_MS:86400000} # 24 hours in milliseconds
