spring:
  application:
    name: login
  # DataSource configuration
  datasource:
    url: jdbc:postgresql://${DB_HOST:127.0.0.1}:${DB_PORT:5433}/${DB_NAME:stoicron_db}
    username: ${DB_USER:stoicron_user}
    password: ${DB_PASSWORD:stoicron_password}
    driver-class-name: org.postgresql.Driver
  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  # Security configuration
  security:
    oauth2:
      client:
      registration:
        github:
          client-id: ${GITHUB_CLIENT_ID:your_github_client_id}
          client-secret: ${GITHUB_CLIENT_SECRET:your_github_client_secret}
          scope: read:user,user:email
    # Github OAuth2 configuration
    

logging:
  level:
    org:
      springframework:
        security: DEBUG
        

server:
  port: ${PORT:5000}



# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
